version: 0.2
phases:
  install:
    commands:
      - echo "Downloading and installing 7-Zip..."
      - curl -o 7z.exe https://www.7-zip.org/a/7z1900-x64.exe
      - dir 7z.exe
      - start /wait 7z.exe /S /y
      - if errorlevel 1 echo "7-Zip installation failed!"
      - echo "7-Zip installation completed."

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm test
      - "C:\\Program Files\\7-Zip\\7z.exe a lambda-package.zip * -xr!buildspec.yml"

  post_build:
    commands:
      - aws lambda update-function-code --function-name github-to-lambda --zip-file fileb://lambda-package.zip

artifacts:
  files:
    - lambda-package.zip
