version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Pre-build phase: No commands to run."
  build:
    commands:
      - echo "Running build phase..."
      - npm install
      - npm test
      - zip -r lambda-package.zip ./ -x "buildspec.yml"
  post_build:
    commands:
      - echo "Running post-build phase..."
      - aws lambda update-function-code --function-name lambda-deployment --zip-file fileb://lambda-package.zip
      - echo "Lambda function updated successfully."
artifacts:
  files:
    - lambda-package.zip
