version: 0.2
phases:
  install:
    commands:
  pre_build:
    commands:
  build:
    commands:
      - npm install
      - npm test
      - zip -r lambda-package.zip ./ -x buildspec.yml
  post_build:
    commands:
      - aws lambda update-function-code --function-name lambda-deployment --zip-file fileb://lambda-package.zip
      - (sleep: 10; aws lambda update-function-configuration --handler app.server --function-name lambda-deployment)
