version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
      
  pre_build:
    commands:
      - echo "Running pre-build tasks..."

  build:
    commands:
      - echo "Running tests..."
      - echo "Creating deployment package..."
      - powershell Compress-Archive -Path * -DestinationPath lambda-package.zip -Force
      - powershell Remove-Item lambda-package.zip
      - powershell Compress-Archive -Path * -DestinationPath lambda-package.zip -Force -Exclude buildspec.yml

  post_build:
    commands:
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name github-to-lambda --zip-file fileb://lambda-package.zip

artifacts:
  files:
    - lambda-package.zip
  discard-paths: no