version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - yum install -y zip 
      - npm install -g aws-cli 
  pre_build:
    commands:
      - echo "Running pre-build phase..."
      - npm install
  build:
    commands:
      - echo "Running build phase..."
      - npm run build
      - zip -r lambda-package.zip . -x "*.git*" "*.log" "buildspec.yml" "*.zip"
  post_build:
    commands:
      - echo "Running post-build phase..."
      - ls -l
      - file lambda-package.zip
      - aws lambda update-function-code --function-name lambda-deployment --zip-file fileb://lambda-package.zip
      - echo "Lambda function code updated successfully"
artifacts:
  files:
    - lambda-package.zip
