version: 0.2
phases:
  install:
    commands:
      - echo "Install phase: No tools to install."
  pre_build:
    commands:
      - echo "Pre-build phase: Installing dependencies."
      - npm install
  build:
    commands:
      - echo "Build phase: Running tests and creating ZIP file."
      - npm test
      - powershell Compress-Archive -Path * -DestinationPath lambda-package.zip -Exclude buildspec.yml
  post_build:
    commands:
      - echo "Post-build phase: Deploying to Lambda."
      - aws lambda update-function-code --function-name github-to-lambda --zip-file fileb://lambda-package.zip
artifacts:
  files:
    - lambda-package.zip

